version: "3"

tasks:
  proto:
    cmds:
      - sh script/proto.sh {{.CLI_ARGS}}
  httpsdk:
    cmds:
      - sh script/httpsdk.sh {{.CLI_ARGS}}
  fmt:
    cmds:
      - sh script/goimports.sh {{ if empty .CLI_ARGS }}all{{ else }}git{{ end }}
    silent: true
  build:
    cmds:
      - goreleaser build --snapshot --single-target --rm-dist
    silent: true
  run:
    deps:
      - build
    cmds:
      - cd cmd && ../dist/grpc-gateway-template_{{OS}}_{{ARCH}}/grpc-gateway-template start --nodaemon
  release:
    cmds:
      - goreleaser release --rm-dist
    silent: true