// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package myservicev1

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/pkg/myservicesdk/pb/mypb"
	"github.com/jaronnie/grpc-gateway-template/pkg/myservicesdk/rest"
)

type HelloGetter interface {
	Hello() HelloInterface
}

type HelloInterface interface {
	SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error)

	HelloExpansion
}

type helloClient struct {
	client rest.Interface
}

func newHelloClient(c *Myservicev1Client) *helloClient {
	return &helloClient{
		client: c.RESTClient(),
	}
}

func (x *helloClient) SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error) {
	var resp mypb.Hello
	err := x.client.Verb("POST").
		SubPath(
			"/api/v1/hello",
		).
		Params().
		Body(param).
		Do(ctx).
		Into(&resp, false)

	if err != nil {
		return nil, err
	}

	return &resp, nil
}
