// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package myservicev1

import (
	"github.com/jaronnie/grpc-gateway-template/pkg/myservicesdk/rest"
)

type Myservicev1Interface interface {
	RESTClient() rest.Interface

	HelloGetter
}

type Myservicev1Client struct {
	restClient rest.Interface
}

func (x *Myservicev1Client) RESTClient() rest.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *Myservicev1Client) Hello() HelloInterface {
	return newHelloClient(x)
}

// NewForConfig creates a new Myservicev1Client for the given config.
func NewForConfig(x *rest.RESTClient) (*Myservicev1Client, error) {
	config := *x
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &Myservicev1Client{client}, nil
}
