# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myservice_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
import hello_pb2 as hello__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='myservice_v1.proto',
  package='mypb',
  syntax='proto3',
  serialized_options=b'Z\006./mypb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12myservice_v1.proto\x12\x04mypb\x1a\x1cgoogle/api/annotations.proto\x1a\x0bhello.proto2F\n\x04\x61pp1\x12>\n\x08SayHello\x12\x0b.mypb.Hello\x1a\x0b.mypb.Hello\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/api/v1/hello:\x01*2F\n\x04\x61pp2\x12>\n\x08SayHello\x12\x0b.mypb.Hello\x1a\x0b.mypb.Hello\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/api/v1/hello:\x01*B\x08Z\x06./mypbb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,hello__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_APP1 = _descriptor.ServiceDescriptor(
  name='app1',
  full_name='mypb.app1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=71,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='mypb.app1.SayHello',
    index=0,
    containing_service=None,
    input_type=hello__pb2._HELLO,
    output_type=hello__pb2._HELLO,
    serialized_options=b'\202\323\344\223\002\022\"\r/api/v1/hello:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APP1)

DESCRIPTOR.services_by_name['app1'] = _APP1


_APP2 = _descriptor.ServiceDescriptor(
  name='app2',
  full_name='mypb.app2',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=143,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='mypb.app2.SayHello',
    index=0,
    containing_service=None,
    input_type=hello__pb2._HELLO,
    output_type=hello__pb2._HELLO,
    serialized_options=b'\202\323\344\223\002\022\"\r/api/v1/hello:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APP2)

DESCRIPTOR.services_by_name['app2'] = _APP2

# @@protoc_insertion_point(module_scope)
