// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/pb/mypb"
)

var (
	FakeReturnSayHello = &mypb.Hello{}
)

type App2Getter interface {
	App2() App2Interface
}

type App2Interface interface {
	SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error)
}

type FakeApp2 struct {
	Fake *FakeMyservicev1
}

func (f *FakeApp2) SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error) {
	return FakeReturnSayHello, nil
}
