// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/pb/mypb"
)

var (
	FakeReturnSayHello = &mypb.Hello{}
)

type App1Getter interface {
	App1() App1Interface
}

type App1Interface interface {
	SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error)
}

type FakeApp1 struct {
	Fake *FakeMyservicev1
}

func (f *FakeApp1) SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error) {
	return FakeReturnSayHello, nil
}
