// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package app2

import (
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app2/rest"
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app2/typed"

	app2v1 "github.com/jaronnie/grpc-gateway-template/httpsdk/app2/typed/app2v1"
)

type Interface interface {
	Direct() typed.DirectInterface

	App2v1() app2v1.App2v1Interface
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	app2v1 *app2v1.App2v1Client
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

func (x *Clientset) App2v1() app2v1.App2v1Interface {
	return x.app2v1
}

func NewClientWithOptions(ops ...rest.Opt) (*Clientset, error) {
	c := &rest.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.app2v1, err = app2v1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	return &cs, nil
}
