// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/rest"
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/typed/app1v1"
)

type FakeApp1v1 struct{}

func (f *FakeApp1v1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeApp1v1) Hello() app1v1.HelloInterface {
	return &FakeHello{Fake: f}
}
