// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/pb/mypb/app1"
)

var (
	FakeReturnSayHello = &app1.Hello{}
)

type HelloGetter interface {
	Hello() HelloInterface
}

type HelloInterface interface {
	SayHello(ctx context.Context, param *app1.Hello) (*app1.Hello, error)
}

type FakeHello struct {
	Fake *FakeApp1v1
}

func (f *FakeHello) SayHello(ctx context.Context, param *app1.Hello) (*app1.Hello, error) {
	return FakeReturnSayHello, nil
}
