// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/typed"
	"github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/typed/fake"

	myservicev1 "github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/typed/myservicev1"
	fakemyservicev1 "github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/typed/myservicev1/fake"
)

type Clientset struct{}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

func (f *Clientset) Myservicev1() myservicev1.Myservicev1Interface {
	return &fakemyservicev1.FakeMyservicev1{}
}
