// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/pkg/myservicesdk/pb/mypb"
)

var (
	FakeReturnSayHello = &mypb.Hello{}
)

type HelloGetter interface {
	Hello() HelloInterface
}

type HelloInterface interface {
	SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error)
}

type FakeHello struct {
	Fake *FakeMyservicev1
}

func (f *FakeHello) SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error) {
	return FakeReturnSayHello, nil
}
