// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"github.com/jaronnie/grpc-gateway-template/pkg/myservicesdk/rest"
	"github.com/jaronnie/grpc-gateway-template/pkg/myservicesdk/typed/myservicev1"
)

type FakeMyservicev1 struct{}

func (f *FakeMyservicev1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeMyservicev1) Hello() myservicev1.HelloInterface {
	return &FakeHello{Fake: f}
}
