// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package app1

import (
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/rest"
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/typed"

	app1v1 "github.com/jaronnie/grpc-gateway-template/httpsdk/app1/typed/app1v1"
)

type Interface interface {
	Direct() typed.DirectInterface

	App1v1() app1v1.App1v1Interface
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	app1v1 *app1v1.App1v1Client
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

func (x *Clientset) App1v1() app1v1.App1v1Interface {
	return x.app1v1
}

func NewClientWithOptions(ops ...rest.Opt) (*Clientset, error) {
	c := &rest.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.app1v1, err = app1v1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	return &cs, nil
}
