// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package myservicev1

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/pb/mypb"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/rest"
)

type App1Getter interface {
	App1() App1Interface
}

type App1Interface interface {
	SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error)

	App1Expansion
}

type app1Client struct {
	client rest.Interface
}

func newApp1Client(c *Myservicev1Client) *app1Client {
	return &app1Client{
		client: c.RESTClient(),
	}
}

func (x *app1Client) SayHello(ctx context.Context, param *mypb.Hello) (*mypb.Hello, error) {
	var resp mypb.Hello
	err := x.client.Verb("POST").
		SubPath(
			"/api/v1/hello",
		).
		Params().
		Body(param).
		Do(ctx).
		Into(&resp, false)

	if err != nil {
		return nil, err
	}

	return &resp, nil
}
