// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package myservicev1

import (
	"github.com/jaronnie/grpc-gateway-template/httpsdk/myservice/rest"
)

type Myservicev1Interface interface {
	RESTClient() rest.Interface

	App1Getter
	App2Getter
}

type Myservicev1Client struct {
	restClient rest.Interface
}

func (x *Myservicev1Client) RESTClient() rest.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *Myservicev1Client) App1() App1Interface {
	return newApp1Client(x)
}

func (x *Myservicev1Client) App2() App2Interface {
	return newApp2Client(x)
}

// NewForConfig creates a new Myservicev1Client for the given config.
func NewForConfig(x *rest.RESTClient) (*Myservicev1Client, error) {
	config := *x
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &Myservicev1Client{client}, nil
}
