// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/typed"
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/typed/fake"

	app1v1 "github.com/jaronnie/grpc-gateway-template/httpsdk/app1/typed/app1v1"
	fakeapp1v1 "github.com/jaronnie/grpc-gateway-template/httpsdk/app1/typed/app1v1/fake"
)

type Clientset struct{}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

func (f *Clientset) App1v1() app1v1.App1v1Interface {
	return &fakeapp1v1.FakeApp1v1{}
}
