// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package fake

import (
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app2/rest"
	"github.com/jaronnie/grpc-gateway-template/httpsdk/app2/typed/app2v1"
)

type FakeApp2v1 struct{}

func (f *FakeApp2v1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeApp2v1) Hello() app2v1.HelloInterface {
	return &FakeHello{Fake: f}
}
