// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package app1v1

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/pb/mypb/app1"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/rest"
)

type App2Getter interface {
	App2() App2Interface
}

type App2Interface interface {
	SayHello(ctx context.Context, param *app1.Hello) (*app1.Hello, error)

	App2Expansion
}

type app2Client struct {
	client rest.Interface
}

func newApp2Client(c *App1v1Client) *app2Client {
	return &app2Client{
		client: c.RESTClient(),
	}
}

func (x *app2Client) SayHello(ctx context.Context, param *app1.Hello) (*app1.Hello, error) {
	var resp app1.Hello
	err := x.client.Verb("POST").
		SubPath(
			"/api/v1/hello",
		).
		Params().
		Body(param).
		Do(ctx).
		Into(&resp, false)

	if err != nil {
		return nil, err
	}

	return &resp, nil
}
