// Code generated by protoc-gen-go-httpsdk. DO NOT EDIT.
package app1v1

import (
	"context"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/pb/mypb/app1"

	"github.com/jaronnie/grpc-gateway-template/httpsdk/app1/rest"
)

type HelloGetter interface {
	Hello() HelloInterface
}

type HelloInterface interface {
	SayHello(ctx context.Context, param *app1.Hello) (*app1.Hello, error)

	HelloExpansion
}

type helloClient struct {
	client rest.Interface
}

func newHelloClient(c *App1v1Client) *helloClient {
	return &helloClient{
		client: c.RESTClient(),
	}
}

func (x *helloClient) SayHello(ctx context.Context, param *app1.Hello) (*app1.Hello, error) {
	var resp app1.Hello
	err := x.client.Verb("POST").
		SubPath(
			"/api/v1/hello",
		).
		Params().
		Body(param).
		Do(ctx).
		Into(&resp, false)

	if err != nil {
		return nil, err
	}

	return &resp, nil
}
